load main
bernatmv/minigames-html5 pull request #17
Opened 2016-11-28 22:22 UTC by AbrahamAlcaina

Send events to server

2016-11-28 23:23 UTC, bernatmv requested changes
Some doubts regarding this PR

2016-11-28 23:23 UTC, bernatmv commented on client/src/js/states/loading.js
> -				this.game.state.start('main');
why do you remove this?

2016-11-28 23:23 UTC, bernatmv commented on client/src/js/states/loading.js
> +            setTimeout(()=>this.game.state.start('main'), 1000);
this is not needed if we start main after the loading process

2016-11-28 23:23 UTC, bernatmv commented on client/src/js/actions.js
> +});
what will be the flow for joining a game? I was thinking about providing a URL that will be posted to someone chat

2016-11-29 08:10 UTC, AbrahamAlcaina commented on client/src/js/actions.js
> +});
In any case we need to send the message of join to the server

2016-11-29 08:13 UTC, AbrahamAlcaina commented on client/src/js/states/loading.js
> -				this.game.state.start('main');
```
        this.game.load.onFileComplete.add(loadCheck);
        this.game.load.onPackComplete.add(loadCheck);
        this.game.load.onLoadComplete.add(() => {
            preloadBar.text = this.game.load.progress + '%';
            //TODO REMOVE
            setTimeout(()=>this.game.state.start('main'), 1000);
        }, this);
```

2016-11-29 13:13 UTC, bernatmv approved these changes

2016-11-29 13:14 UTC, merged